# Import necessary libraries
import dash
import os
from dash import html, dcc
import pandas as pd
import base64
import dash_bootstrap_components as dbc

# Create a Dash application
app = dash.Dash(__name__,  external_stylesheets=[dbc.themes.BOOTSTRAP])

def encode_image(image_filename):
    with open(image_filename, 'rb') as f:
        image = f.read()
    return base64.b64encode(image).decode('utf-8')

# Sample data for the periodic table (a full version would contain all elements)
data = {
    'Symbol': ['H', 'He', 'Li', 'Be', 'B', 'C', 'N', 'O', 'F', 'Ne'],
    'AtomicNumber': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Element': ['Hydrogen', 'Helium', 'Lithium', 'Beryllium', 'Boron', 'Carbon', 'Nitrogen', 'Oxygen', 'Fluorine', 'Neon']
}

vp="Italian chemist Alessandro Volta invented the Voltaic Pile to win an argument with biologist Luigi Galvani. Volta wanted to prove to Galvani that electricity was generated by metals and not from some animal spirit, as he believed then."
battery_hist = {
    "Name":["Voltaic Pile","Lead acid"],
    "Year":["1799","1859"],
    "Scientist":["Alessandro Volta"],
    "Anode":["Zinc (Zn)"],
    "Cathode":["Copper (Cu)"],
    "Info":[vp]
}


df = pd.DataFrame(data)
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
img_path = os.path.join(BASE_DIR, 'assets/gaston_plante.jpg')
img_src = "data:image/jpeg;base64," + encode_image(img_path)
# Layout for the application
app.layout = html.Div([
            dbc.Row(
                [
                dbc.Col(html.Img(src=img_src, style={'width': '300px', 'height': '250px'}, width=3 )),
                dbc.Col(html.H1("BATTERIES",
                                # style={
                                #     # 'textAligns': 'left',
                                #     # 'padding': '20px',        # Padding all around
                                #     # 'border': '1px solid black',  # Black border of 2px thickness
                                #     'backgroundColor': '#f9e4f9',  # Light gray background color
                                #     'width': '100%'}         # Set width
                            )),
                ]
                ,  style={
                                    # 'textAligns': 'left',
                                    'padding': '3spx',        # Padding all around
                                    'border': '1px solid pink',  # Black border of 2px thickness
                                    'backgroundColor': '#f9e4f9',  # Light gray background color
                                    'width': '100%'}
            ),
            # html.Img(src=img_src, style={'width': '300px', 'height': '250px'} ),
            # html.H1("Battery", style={'textAlign': 'center'}),

            html.Table(
                # Header
                [html.Tr([html.Th(col) for col in df.columns])] +

                # Body
                [html.Tr([
                    html.Td(df.iloc[i][col]) for col in df.columns
                ]) for i in range(len(df))]
            )
])

# Running the application
if __name__ == '__main__':
    app.run_server(debug=True)
